name: Test & lint

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: ${{ vars.RYE_VERSION }}
          RYE_TOOLCHAIN_VERSION: cpython@${{ matrix.python-version }}
          RYE_INSTALL_OPTION: "--yes"

      - name: Install dependencies
        run: |
          rye sync --all-features

      - name: Run lint
        run: |
          rye run lint

      - name: Run tests
        run: |
          rye run test

      - name: Ensure importable
        run: |
          rye run python -c 'import pyyoutube'
